unlink('docs', recursive = TRUE)
dir.create('docs')
file.copy("udclogo.png", "docs")
file.copy("icologo.png", "docs")
file.copy("linkedinlogo.png", "docs")
file.copy("githublogo.png", "docs")
file.copy("Researchgatelogo.png", "docs")
file.copy("orcidlogo.png", "docs")
file.copy("logo.png", "docs")
file.copy("imagenes", "docs/", recursive=TRUE)

