project:
  output-dir: ../docs/en
  
title: "Final Master’s Project"
subtitle: "Application of artificial neural networks and quadratic programming in portfolio management"
author: 
  - name: David Díaz Rodríguez
    affiliations:
      - id: udc
        name: University of A Coruña 
        city: La Coruña
        state: Galicia
    orcid: https://orcid.org/0000-0002-0927-9795
    email: david.diazr@udc.es
  - name: Xosé Manuel Martínez Filgueira
    affiliations:
      - ref: udc
    orcid: https://orcid.org/0000-0003-2452-4864
    email: xose.martinez@udc.es
format: 
  revealjs:
    logo: ../logo.png
    footer: David Díaz Rodríguez [![](../linkedinlogo.png){fig-alt="Linkedin profile" width=15px src=../linkedinlogo.png style="margin-bottom:0;"}](https://www.linkedin.com/in/david-d-6257951b8) [![](../githublogo.png){fig-alt="Github ptoject" width=15px src=../githublogo.png style="margin-bottom:0;"}](https://github.com/davidrsch/tfm-slides) [![](../Researchgatelogo.png){fig-alt="ResearchGate profile" width=15px src=../Researchgatelogo.png style="margin-bottom:0;"}](https://www.researchgate.net/profile/David-Diaz-Rodriguez) [![](../orcidlogo.png){fig-alt="ORCid profile" width=15px src=../orcidlogo.png style="margin-bottom:0;"}](https://orcid.org/0000-0002-0927-9795) 
    multiplex: false
    controls: true
    navigation-mode: linear
    transition: slide
    menu: 
      custom:
        - title: 'Language'
          icon: '<i class="fa fa-language">'
          content: '<ul class="slide-menu-items"><li class="slide-menu-item" data-item="0" ><a href="../index.html"><span class="slide-menu-item-title">Español</span></a></li><li class="slide-menu-item" data-item="0" ><a href="../gal/index.html"><span class="slide-menu-item-title">Galego</span></a></li></ul>'
    chalkboard:
      theme: whiteboard
      boardmarker-width: 5
    include-after-body: style_and_scripts_after.html
    include-in-header: 
      - text: <link rel="icon" type="image/x-icon" href="../icologo.png">